#!/bin/sh
set -efu
blaslib=$(update-alternatives --list libblas.so.3 | grep $(basename $0))
update-alternatives --set libblas.so.3 $blaslib

# one python is enough
PYS=${PYS:-"$(pyversions -d 2>/dev/null)"}

#test only modules that link against libblas
PYS=$PYS TESTPKG=numpy.core debian/tests/python2
PYS=$PYS TESTPKG=numpy.linalg debian/tests/python2
